#!/usr/bin/env ruby
# encoding: UTF-8
require 'socket'

cols = `tput cols`
seperator = (1..cols.to_i/4).inject("") {|x| x << "🐱   " }
seperator = "\n%s\n" % seperator

COMMAND = ARGV.join(" ")

def execute_command
  system "clear"
  system COMMAND
end

execute_command

Socket.tcp_server_loop(5326) {|sock, client_addrinfo|
  begin
    puts seperator
    execute_command
  ensure
    sock.close
  end
}

