require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExamDatesController do

  # This should return the minimal set of attributes required to create a valid
  # ExamDate. As you add validations to ExamDate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "event" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExamDatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all exam_dates as @exam_dates" do
      exam_date = ExamDate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exam_dates).should eq([exam_date])
    end
  end

  describe "GET show" do
    it "assigns the requested exam_date as @exam_date" do
      exam_date = ExamDate.create! valid_attributes
      get :show, {:id => exam_date.to_param}, valid_session
      assigns(:exam_date).should eq(exam_date)
    end
  end

  describe "GET new" do
    it "assigns a new exam_date as @exam_date" do
      get :new, {}, valid_session
      assigns(:exam_date).should be_a_new(ExamDate)
    end
  end

  describe "GET edit" do
    it "assigns the requested exam_date as @exam_date" do
      exam_date = ExamDate.create! valid_attributes
      get :edit, {:id => exam_date.to_param}, valid_session
      assigns(:exam_date).should eq(exam_date)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExamDate" do
        expect {
          post :create, {:exam_date => valid_attributes}, valid_session
        }.to change(ExamDate, :count).by(1)
      end

      it "assigns a newly created exam_date as @exam_date" do
        post :create, {:exam_date => valid_attributes}, valid_session
        assigns(:exam_date).should be_a(ExamDate)
        assigns(:exam_date).should be_persisted
      end

      it "redirects to the created exam_date" do
        post :create, {:exam_date => valid_attributes}, valid_session
        response.should redirect_to(ExamDate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exam_date as @exam_date" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExamDate.any_instance.stub(:save).and_return(false)
        post :create, {:exam_date => { "event" => "invalid value" }}, valid_session
        assigns(:exam_date).should be_a_new(ExamDate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExamDate.any_instance.stub(:save).and_return(false)
        post :create, {:exam_date => { "event" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exam_date" do
        exam_date = ExamDate.create! valid_attributes
        # Assuming there are no other exam_dates in the database, this
        # specifies that the ExamDate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExamDate.any_instance.should_receive(:update_attributes).with({ "event" => "" })
        put :update, {:id => exam_date.to_param, :exam_date => { "event" => "" }}, valid_session
      end

      it "assigns the requested exam_date as @exam_date" do
        exam_date = ExamDate.create! valid_attributes
        put :update, {:id => exam_date.to_param, :exam_date => valid_attributes}, valid_session
        assigns(:exam_date).should eq(exam_date)
      end

      it "redirects to the exam_date" do
        exam_date = ExamDate.create! valid_attributes
        put :update, {:id => exam_date.to_param, :exam_date => valid_attributes}, valid_session
        response.should redirect_to(exam_date)
      end
    end

    describe "with invalid params" do
      it "assigns the exam_date as @exam_date" do
        exam_date = ExamDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExamDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => exam_date.to_param, :exam_date => { "event" => "invalid value" }}, valid_session
        assigns(:exam_date).should eq(exam_date)
      end

      it "re-renders the 'edit' template" do
        exam_date = ExamDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExamDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => exam_date.to_param, :exam_date => { "event" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exam_date" do
      exam_date = ExamDate.create! valid_attributes
      expect {
        delete :destroy, {:id => exam_date.to_param}, valid_session
      }.to change(ExamDate, :count).by(-1)
    end

    it "redirects to the exam_dates list" do
      exam_date = ExamDate.create! valid_attributes
      delete :destroy, {:id => exam_date.to_param}, valid_session
      response.should redirect_to(exam_dates_url)
    end
  end

end
